# Generated by Django 5.2.7 on 2025-10-28 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0005_exposurealert_bookings_ex_user_id_e0bd40_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("currency", models.CharField(default="AUD", max_length=8)),
                ("subtotal_cents", models.IntegerField(default=0)),
                ("tax_cents", models.IntegerField(default=0)),
                ("total_cents", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                        ],
                        default="sandbox",
                        max_length=20,
                    ),
                ),
                ("amount_cents", models.IntegerField()),
                ("currency", models.CharField(default="AUD", max_length=8)),
                (
                    "provider_intent_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "provider_charge_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_action", "Requires Action"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled"),
                        ],
                        default="requires_action",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["booking", "status"],
                        name="payments_pa_booking_57d6de_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_intent_id"],
                        name="payments_pa_provide_123350_idx",
                    ),
                ],
            },
        ),
    ]
