# Generated by Django 5.2.7 on 2025-10-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('citizenship', models.CharField(blank=True, max_length=64)),
                ('covid_status', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not vaccinated'), ('undisclosed', 'Undisclosed')], default='undisclosed', max_length=20)),
                ('consent', models.JSONField(blank=True, default=dict)),
                ('address', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
