# Generated by Django 5.2.7 on 2025-10-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
