# Generated by Django 5.2.7 on 2025-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_totp_enabled_userprofile_totp_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="covid_status",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consent_healthdata",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consent_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consent_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consent_version",
            field=models.CharField(blank=True, default="v1", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="covid_vaccinated",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
