# Generated by Django 5.2.7 on 2025-10-22 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_userprofile_covid_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="vaccination_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload your COVID vaccination certificate (PDF only).",
                null=True,
                upload_to="vaccination/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vaccination_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vaccination_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set by staff after manual review of the uploaded certificate.",
            ),
        ),
    ]
