# Generated by Django 5.2.7 on 2025-10-12 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('General', 'General'), ('Package', 'Package'), ('Specific', 'Specific')], max_length=16)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('InProgress', 'InProgress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Draft', max_length=16)),
                ('preferred_dates', models.JSONField(blank=True, default=list)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('quoted_price_cents', models.IntegerField(blank=True, null=True)),
                ('budget_cents', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.servicepackage')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
