# Generated by Django 5.2.7 on 2025-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_budget_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
