# Generated by Django 5.2.7 on 2025-10-23 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_contactevent_exposurealert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exposurealert",
            index=models.Index(
                fields=["user", "acknowledged_at", "expires_at"],
                name="bookings_ex_user_id_e0bd40_idx",
            ),
        ),
    ]
