# Generated by Django 5.2.7 on 2025-10-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="anonymous",
        ),
    ]
